// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SmartHomeLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_SmartHomeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SmartHomeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SmartHomeLabel, -6);
    lv_obj_set_y(ui_SmartHomeLabel, -224);
    lv_obj_set_align(ui_SmartHomeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SmartHomeLabel, "Smart Home");
    lv_obj_set_style_text_color(ui_SmartHomeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SmartHomeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SmartHomeLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);


}
